import { prisma } from '@/lib/prisma';
import { NextResponse } from 'next/server';
import Papa from 'papaparse';

export async function POST(request: Request) {
    try {
        const formData = await request.formData();
        const file = formData.get('file') as File;

        if (!file) {
            return NextResponse.json(
                { error: 'File is required' },
                { status: 400 },
            );
        }

        const text = await file.text();

        // Simple delimiter detection
        const firstLine = text.split('\n')[0];
        const delimiter = firstLine.includes(';') ? ';' : ',';

        const { data, errors } = Papa.parse(text, {
            header: true,
            skipEmptyLines: true,
            delimiter,
        });

        if (errors.length > 0) {
            console.warn('CSV parsing errors (ignoring, but logging):', errors);
        }

        const emailMap = new Map<string, any>();

        // Deduplicate within CSV and normalize emails
        (data as any[]).forEach((row) => {
            const email = (row.email || row.Email || row['E-mailadres'] || '')
                .trim()
                .toLowerCase();

            if (email && !emailMap.has(email)) {
                emailMap.set(email, row);
            }
        });

        const uniqueEmails = Array.from(emailMap.keys());

        // Find existing contacts
        const existingContacts = await prisma.contact.findMany({
            where: {
                email: { in: uniqueEmails },
            },
            select: { email: true },
        });

        const existingEmailSet = new Set(
            existingContacts.map((c) => c.email.toLowerCase()),
        );

        const newContacts: any[] = [];
        let skippedCount = 0;

        for (const [email, row] of emailMap) {
            if (existingEmailSet.has(email)) {
                skippedCount++;
                continue;
            }

            // Map fields (handling English and Dutch headers)
            newContacts.push({
                email,
                firstName:
                    row.firstName || row.first_name || row.Voornaam || null,
                lastName:
                    row.lastName || row.last_name || row.Achternaam || null,
                status: row.status || row.Status || 'SUBSCRIBED',
                source: row.source || row.Source || 'IMPORT',
                updatedAt: new Date(),
                // Generate token manually if needed for bulk ops, although schema default might handle it
                // unsubscribeToken is generated by DB default if using createMany?
                // Creating one by one or batch
            });
        }

        // Batch create new contacts
        // Note: createMany is faster but requires handling defaults.
        // We'll trust Prisma/DB defaults where possible, but loop if needed.
        // For Postgres, createMany is supported.
        if (newContacts.length > 0) {
            await prisma.contact.createMany({
                data: newContacts,
                skipDuplicates: true,
            });
        }

        return NextResponse.json({
            success: true,
            imported: newContacts.length,
            skipped: data.length - newContacts.length,
            total: data.length,
        });
    } catch (error) {
        console.error('Import error:', error);
        return NextResponse.json(
            { error: 'Failed to import contacts' },
            { status: 500 },
        );
    }
}
